export const ActionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
    ADD_CART: 'ADD_CART',
    REMOVE_CART: 'REMOVE_CART',
    ADD_TOTAL_PRICE: 'ADD_TOTAL_PRICE',
    UPDATE_TOTAL_PRICE: 'UPDATE_TOTAL_PRICE',
}